FROM python:3.7.0

ENV WORKSPACE /src
WORKDIR $WORKSPACE
ENV NATS_SERVER_URL=nats://cluster-nats-client.opni.svc.cluster.local:4222
ENV NATS_USERNAME=nats-user
ENV NATS_PASSWORD=

RUN pip install --upgrade pip

COPY ["/payload-receiver-service/tests/integration/requirements.txt", "$WORKSPACE/payload-receiver-service/tests/integration/requirements.txt"]

RUN cd $WORKSPACE && \
    pip install -r payload-receiver-service/tests/integration/requirements.txt

COPY [".", "$WORKSPACE"]

RUN cd $WORKSPACE && ls && \
    chmod +x ./payload-receiver-service/tests/integration/run_sono.sh

ENTRYPOINT ["./payload-receiver-service/tests/integration/run_sono.sh"]
